### ISSUE TITLE
PHP Fatal error:  Class 'Ponticlaro\Bebop\HttpApi\Bebop' not found

### ISSUE THREAD

**Issue by jrconway3** [ponticlaro/bebop-http-api#1]
```
[29-Sep-2015 06:49:31 UTC] PHP Fatal error:  Class 'Ponticlaro\Bebop\HttpApi\Bebop' not found in /home/jaidynreiman/Personal/contract/ponticlaro/websites/bh/bleeding-heartland-www/app/vendor/ponticlaro/bebop-http-api/src/HttpApi/Router.php on line 135
```

I'm getting this fatal error when trying to add comments on Bleeding Heartland. The issue seems to be that Ponticlaro\Bebop has not been initialized on Router. I've tested it by adding Ponticlaro\Bebop myself:

```
namespace Ponticlaro\Bebop\HttpApi;

use Ponticlaro\Bebop;
use Ponticlaro\Bebop\Common\Collection;
use Ponticlaro\Bebop\HttpApi\Exceptions\BaseException;
```

And it does work. I would've pushed trough this fix myself, but I'm not sure what effect that would cause elsewhere, so I opted to leave it to you instead. I have tested this locally and this does fix the comments error over at Bleeding Heartland.

**Comment by cristianobaptista** [comment]
Fixed via ec33e73f43e365df485c6ca024b76fe00db642e1
